import React, { createContext, useContext, useState, ReactNode } from 'react';
import { useSiteContent } from './SiteContentContext';

type Language = 'ro' | 'en' | 'ru';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
  getDetailLabel: (label: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

const STORAGE_KEY = 'app_lang';

// Helper to detect browser language
const getBrowserLanguage = (): Language => {
  const browserLang = navigator.language.toLowerCase();
  if (browserLang.startsWith('ru')) return 'ru';
  if (browserLang.startsWith('en')) return 'en';
  return 'ro'; // default
};

// Helper to get initial language
const getInitialLanguage = (): Language => {
  const stored = localStorage.getItem(STORAGE_KEY);
  if (stored && ['ro', 'en', 'ru'].includes(stored)) {
    return stored as Language;
  }
  return getBrowserLanguage();
};

interface LanguageProviderProps {
  children: ReactNode;
}

export const LanguageProvider: React.FC<LanguageProviderProps> = ({ children }) => {
  const [language, setLanguageState] = useState<Language>(getInitialLanguage);
  const { getTextOverride } = useSiteContent();

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem(STORAGE_KEY, lang);
  };

  // Translation function
  const t = (key: string): string => {
    const override = getTextOverride(language, key) || getTextOverride('ro', key);
    if (override) return override;

    const keys = key.split('.');
    let value: any = translations[language];
    
    for (const k of keys) {
      if (value && typeof value === 'object' && k in value) {
        value = value[k];
      } else {
        // Fallback to Romanian if key not found
        value = translations['ro'];
        for (const fallbackKey of keys) {
          if (value && typeof value === 'object' && fallbackKey in value) {
            value = value[fallbackKey];
          } else {
            // Return key itself if not found in fallback
            return key;
          }
        }
        break;
      }
    }
    
    return typeof value === 'string' ? value : key;
  };

  const getDetailLabel = (label: string): string => {
    const ro = (translations['ro'] as any)?.gallery?.detailLabels;
    const lang = (translations[language] as any)?.gallery?.detailLabels;
    if (lang && typeof lang[label] === 'string') return lang[label];
    if (ro && typeof ro[label] === 'string') return ro[label];
    return label;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t, getDetailLabel }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = (): LanguageContextType => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};

// Translation dictionaries
const translations: Record<Language, any> = {
  ro: {
    nav: {
    home: 'Acasă',
    products: 'Galerie',
      about: 'Despre',
      contact: 'Contact',
      favorites: 'Favorite',
      tryRoom: 'Testează în camera mea',
      admin: 'Admin',
      logout: 'Deconectare',
    },
    hero: {
      title: 'RightMob',
      subtitle: 'Transformă-ți spațiul cu mobilier de lux creat pentru confort și stil inegalabil',
      cta: 'Explorează colecția',
      stats: {
        happyClients: 'Clienți mulțumiți',
        products: 'Produse premium',
        experience: 'Ani de experiență',
      },
    },
    tryRoom: {
      title: 'Testează mobila în camera ta',
      subtitle: 'Vezi cum arată mobilierul nostru în propriul tău spațiu înainte de a cumpăra',
      cta: 'Încearcă acum',
      previewBadge: 'Live',
      previewTitle: 'Previzualizare live',
      previewSubtitle: 'Poziționează mobila în câteva secunde',
      previewAlt: 'Previzualizare mobilier in camera',
    },
    videoSection: {
      badge: 'Descoperă povestea noastră',
      title: 'Excelență în\nfiecare detaliu',
      description: 'Fiecare piesă de mobilier RightMob este rezultatul unei pasiuni profunde pentru design, materiale premium și atenție desăvârșită la detalii. De la concept la realizare, creăm spații care inspiră.',
      cta: 'Solicită o consultație',
      stat1Label: 'Proiecte finalizate',
      stat2Label: 'Satisfacție clienți',
    },
    currency: {
      changeLabel: 'Schimbă valuta prețului',
    },
    collections: {
      title: 'Colecțiile noastre',
      subtitle: 'Mobilier de calitate pentru casă și birou',
      viewAll: 'Vezi galerie',
      viewDetails: 'Vezi detalii',
      itemsLabel: 'imagini',
      cards: {
        living: {
          title: 'Living',
          description: 'Confort și eleganță pentru spațiul tău de relaxare',
        },
        bedroom: {
          title: 'Dormitor',
          description: 'Oază de liniște și stil pentru un somn perfect',
        },
        kitchen: {
          title: 'Bucătărie',
          description: 'Design funcțional pentru inima casei tale',
        },
      },
    },
    whyUs: {
      badge: 'De ce RIGHT MOB?',
      title: 'Excelență în fiecare aspect',
      subtitle: 'Mobilier bine făcut, livrare și montaj la locul tău.',
      quality: {
        title: 'Calitate premium',
        description: 'Materiale bune, execuție atentă.',
      },
      warranty: {
        title: 'Garanție 10 ani',
        description: 'Oferim garanție de 10 ani pe produsele noastre.',
      },
      delivery: {
        title: 'Livrare gratuită',
        description: 'Livrare gratuită pentru comenzi peste 5000 RON.',
      },
      design: {
        title: 'Design unic',
        description: 'Piese făcute la comandă, după proiectul tău.',
      },
      stats: {
        satisfaction: 'Satisfacție client',
        delivery: 'Livrare rapidă',
        experience: 'Ani experiență',
        rating: 'Rating mediu',
      },
    },
    testimonials: {
      title: 'Ce spun clienții noștri',
      subtitle: 'Părerile clienților despre colaborarea cu noi.',
      empty: 'Nu există recenzii încă.',
    },
    products: {
      title: 'Produsele noastre',
      all: 'Toate',
      search: 'Caută produse...',
      noResults: 'Nu am găsit produse care să se potrivească criteriilor tale',
      tryAgain: 'Încearcă să ajustezi filtrele sau caută altceva',
      addToFavorites: 'Adaugă la favorite',
      removeFromFavorites: 'Șterge din favorite',
      productsCount: 'imagini',
      filters: {
        title: 'Filtre',
        reset: 'Resetează',
        categories: 'Categorii',
        priceRange: 'Interval preț',
        min: 'Minim',
        max: 'Maxim',
        quick: 'Filtre rapide',
        newest: 'Produse noi',
        bestseller: 'Bestseller',
      },
      sort: {
        recommended: 'Recomandate',
        newest: 'Cele mai noi',
        priceAsc: 'Preț crescător',
        priceDesc: 'Preț descrescător',
        rating: 'Rating',
        name: 'Nume A-Z',
      },
      view: {
        grid: 'Vizualizare grid',
        list: 'Vizualizare listă',
      },
      empty: {
        title: 'Nu am găsit produse',
        subtitle: 'Încearcă să ajustezi filtrele pentru a vedea mai multe rezultate',
        reset: 'Resetează filtrele',
      },
      badges: {
        new: 'Nou',
        bestseller: 'Bestseller',
      },
      reviews: 'recenzii',
      categories: {
        all: 'Toate',
        living: 'Living',
        bedroom: 'Dormitor',
        dining: 'Bucătărie',
        office: 'Birou',
        hall: 'Hol',
        bathroom: 'Baie',
        kids: 'Cameră Copii',
        garden: 'Grădină',
      },
    },
    productDetail: {
      loading: 'Se încarcă...',
      notFoundTitle: 'Produsul nu a fost găsit',
      backToProducts: 'Înapoi la galerie',
      newBadge: 'Nou',
      zoomHint: 'Click pentru zoom',
      bestseller: 'Bestseller',
      inStock: 'În stoc',
      outOfStock: 'Stoc epuizat',
      saveLabel: 'Economisești',
      colorAvailable: 'Culoare disponibilă',
      colorsAvailable: 'Culori disponibile',
      soldOut: 'Epuizat',
      deliveryTitle: 'Livrare Gratuită',
      deliverySubtitle: 'În 2-3 zile lucrătoare',
      warrantyTitle: 'Garanție 10 Ani',
      warrantySubtitle: 'Produse de calitate',
      featuresTitle: 'Caracteristici',
      materialsTitle: 'Materiale',
      dimensionsTitle: 'Dimensiuni',
      widthLabel: 'Lățime',
      heightLabel: 'Înălțime',
      depthLabel: 'Adâncime',
      relatedTitle: 'Produse Similare',
      reviewsTitle: 'Recenzii',
      noReviews: 'Niciună recenzie afișată.',
      ratingLabel: 'Rating',
      reviewTitleLabel: 'Titlu recenzie',
      reviewTitlePlaceholder: 'Rezumat scurt (opțional)',
      addComment: 'Adaugă un comentariu',
      reviewDetailsHint: 'Descrie pe scurt experiența, calitatea și livrarea.',
      authorPlaceholder: 'Nume (opțional)',
      iAmOwner: 'Sunt proprietarul acestui produs',
      submitReview: 'Trimite',
      reviewSent: 'Mulțumim! Recenzia ta a fost adăugată.',
    },
    favorites: {
      title: 'Galeria Ta Favorite',
      empty: 'Nu ai imagini favorite încă',
      emptyDesc: 'Începe să explorezi galeria și adaugă imaginile tale preferate',
      browse: 'Răsfoiește Galeria',
      view: 'Vezi',
      remove: 'Elimină din favorite',
      backToProducts: 'Înapoi la galerie',
    },
    gallery: {
      title: 'Mobilier',
      fromOurGallery: 'Din galeria noastră',
      sortBy: 'Sortează',
      sortNewest: 'Cele mai noi',
      sortNameAsc: 'Nume A → Z',
      sortNameDesc: 'Nume Z → A',
      sortCategory: 'Categorie',
      all: 'Toate',
      product: 'produs',
      products: 'produse',
      inCategory: 'în',
      noProducts: 'Niciun produs aici',
      noProductsHint: 'Adaugă produse din panoul de administrare.',
      noProductsInCategory: 'Nu există produse în categoria „{category}".',
      showAllCategories: 'Arată toate categoriile',
      viewDetails: 'Vezi detalii',
      backToGallery: 'Înapoi la galerie',
      details: 'Detalii',
      aboutProject: 'Despre proiect',
      loading: 'Se încarcă...',
      notFound: 'Produsul nu a fost găsit',
      notFoundHint: 'Poate a fost eliminat sau linkul este incorect.',
      noDescription: 'Fără descriere',
      images: 'imagini',
      moreImages: 'imagini',
      reviewsTitle: 'Recenzii',
      noReviews: 'Niciună recenzie afișată.',
      categories: { living: 'Cameră de zi', dormitor: 'Dormitor', bucatarie: 'Bucătărie', birou: 'Birou', office: 'Birou', hol: 'Hol', baie: 'Baie', copii: 'Cameră Copii', gradina: 'Grădină' },
      detailLabels: {
        'Tip': 'Tip',
        'Descriere': 'Descriere',
        'Țara de origine': 'Țara de origine',
        'Producător': 'Producător',
        'Formă bucătărie': 'Formă bucătărie',
        'Material fațadă': 'Material fațadă',
        'Material carcasă': 'Material carcasă',
        'Culoare': 'Culoare',
        'Sistem deschidere': 'Sistem deschidere',
        'Tip sertare': 'Tip sertare',
        'Balamale': 'Balamale',
        'Cornisă': 'Cornisă',
        'Mânere': 'Mânere',
        'Blat': 'Blat',
        'Glisiere': 'Glisiere',
        'Termen de fabricare': 'Termen de fabricare',
        'Proiect': 'Proiect',
        'Materiale fațadă': 'Materiale fațadă',
        'Tip sertare / glisiere': 'Tip sertare / glisiere',
        'Produs': 'Produs',
        'Dimensiuni': 'Dimensiuni',
        'Material': 'Material',
      },
    },
    contact: {
      title: 'Contactează-ne',
      subtitle: 'Avem întrebări? Ne-ar face plăcere să auzim de la tine',
      formTitle: 'Trimite-ne un mesaj',
      formSubtitle: 'Completează formularul și te contactăm rapid',
      name: 'Nume complet',
      email: 'Email',
      phone: 'Telefon',
      optional: 'opțional',
      message: 'Mesajul tău',
      messagePlaceholder: 'Descrie-ne ce tip de mobilier cauți, pentru ce spațiu și ce stil preferi...',
      send: 'Trimite mesaj',
      sending: 'Se trimite...',
      success: 'Mesaj trimis cu succes!',
      error: 'A apărut o eroare. Te rugăm să încerci din nou.',
      privacy: 'Prin trimiterea formularului ești de acord cu prelucrarea datelor în conformitate cu politica de confidențialitate.',
      badge: 'Suntem aici pentru tine',
      followUs: 'Urmărește-ne',
      socialSubtitle: 'Rămâi la curent cu produsele și ofertele noi',
      placeholders: {
        name: 'Ion Popescu',
        email: 'ion@email.com',
        phone: '+373 69 123 456',
      },
      showroom: {
        title: 'Oficiu',
        line1: 'Strada Ștefan cel Mare nr. 123',
        line2: 'Chișinău, Moldova',
        hours: 'Luni – Sâmbătă: 10:00 – 20:00',
      },
      openInMaps: 'Deschide în Google Maps',
      phoneHours: 'Luni – Vineri: 09:00 – 18:00',
      emailHours: 'Răspundem în 24h',
      info: {
        email: 'Email',
        phone: 'Telefon',
        address: 'Adresă',
      },
    },
    about: {
      title: 'Despre RIGHT MOB',
      badge: 'Povestea noastră',
      subtitle: 'Cu peste 15 ani de experiență, aducem eleganță, calitate și design autentic în casele clienților noștri.',
      storyTitle: 'Pasiunea pentru frumos',
      storyText1: 'Totul a început din dorința de a transforma spațiile de locuit în locuri pline de personalitate și confort. Colaborăm cu designeri și producători de încredere pentru a aduce mobilier premium, bine gândit și durabil.',
      storyText2: 'Oferim nu doar piese de mobilier, ci soluții complete pentru living, dormitor, bucătărie și birou – de la selecție la livrare și montare.',
      stats: {
        experience: 'Ani experiență',
        clients: 'Clienți fericiți',
        delivered: 'Piese livrate',
      },
      valuesTitle: 'Valorile noastre',
      values: {
        quality: { title: 'Calitate premium', desc: 'Standarde înalte de producție și materiale alese' },
        passion: { title: 'Pasiune', desc: 'Dedicare pentru fiecare proiect și client' },
        innovation: { title: 'Inovație', desc: 'Design contemporan și funcțional' },
      },
      deliveryTitle: 'Livrare & montare',
      deliverySteps: {
        step1: { title: 'Comandă confirmată', desc: 'Confirmare în maxim 2 ore' },
        step2: { title: 'Pregătire & verificare', desc: 'Produse verificate și ambalate cu grijă' },
        step3: { title: 'Livrare gratuită', desc: 'Transport în 2-3 zile lucrătoare' },
        step4: { title: 'Montare profesională', desc: 'Echipa noastră montează la locul tău' },
      },
      schedule: 'Program montare:',
      scheduleTime: 'Luni – Vineri, 09:00 – 17:00. Programare flexibilă.',
      ctaText: 'Vrei să discutăm despre proiectul tău?',
      ctaButton: 'Contactează-ne',
      whoWeAre: 'Cine suntem noi?',
      customFurnitureTitle: 'Mobilier la comandă, gândit pentru tine',
      whoWeAreP1: 'Suntem o companie specializată în producerea mobilierului la comandă, dedicată creării unor soluții personalizate care îmbină funcționalitatea, estetica și durabilitatea. Lucrăm direct cu fiecare client pentru a transforma ideile, schițele sau necesitățile de spațiu în piese de mobilier realizate exact pe dimensiuni, stil și buget.',
      whoWeAreP2: 'Realizăm mobilier pentru locuințe, spații comerciale și proiecte speciale, acoperind întregul proces: consultanță, proiectare, alegerea materialelor, producție și montaj. Fiecare lucrare este executată cu atenție la detalii, utilizând materiale de calitate și tehnologii moderne, pentru a asigura rezistență în timp și un finisaj impecabil.',
      whoWeAreP3: 'Credem că mobilierul nu trebuie să fie doar frumos, ci și adaptat modului real de utilizare. De aceea, fiecare proiect este gândit practic, optimizat pentru spațiul disponibil și realizat astfel încât să ofere confort, eficiență și identitate fiecărui interior.',
      missionLabel: 'Misiunea noastră',
      missionQuote: 'Misiunea noastră este să oferim clienților soluții corecte, bine executate și durabile, construind relații bazate pe încredere, transparență și profesionalism.',
      whyChooseUs: 'De ce să ne alegeți?',
      whyChooseUsTitle: 'Proces complet, de la idee la montaj',
      whyChooseUsP1: 'Acoperim întregul proces: de la consultanță și proiectare până la producție și montaj. Fiecare lucrare este gândită practic și optimizată pentru spațiul tău, cu materiale de calitate și finisaj impecabil.',
      whyChooseUsP2: 'Construim relații pe termen lung bazate pe încredere, transparență și profesionalism.',
    },
    tryRoomPage: {
      title: 'Try in My Room',
      back: 'Înapoi',
      chooseMode: 'Alege modul de capturare',
      useCamera: 'Folosește Camera',
      uploadImage: 'Încarcă Imagine',
      loadingCamera: 'Se încarcă camera...',
      uploadAnImage: 'Încarcă o imagine',
      redo: 'Refă',
      delete: 'Șterge',
      export: 'Export',
      preparingImage: 'Se pregătește imaginea...',
      upload: 'Încarcă',
      takePhoto: 'Fă poză',
      switch: 'Comută',
      chooseProduct: 'Alege un produs',
      dragUp: '👆 Trage în sus',
      searchPlaceholder: 'Caută produse...',
      allCategories: 'Toate',
      outOfStock: 'Stoc epuizat',
      noProducts: 'Nu s-au găsit produse',
      helpLabel: 'Ajutor',
      helpTitle: 'Cum folosești',
      helpStep1Title: 'Fă o poză',
      helpStep1Desc: 'Folosește camera sau încarcă o imagine a camerei tale',
      helpStep2Title: 'Adaugă mobilă',
      helpStep2Desc: 'Selectează produse din drawer-ul de jos',
      helpStep3Title: 'Aranjează',
      helpStep3DescDesktop: 'Desktop:',
      helpStep3DescDesktopDetails: 'Click & drag, Mouse wheel = zoom, Shift + wheel = rotire',
      helpStep3DescMobile: 'Mobile:',
      helpStep3DescMobileDetails: '1 deget = mutare, 2 degete = zoom & rotire',
      helpStep4Title: 'Export',
      helpStep4Desc: 'Descarcă imaginea finală cu butonul Export',
      colorSelectorTitle: 'Alege culoarea',
      colorSelectorSubtitle: 'Selectează culoarea dorită pentru acest produs',
    },
    auth: {
      login: 'Autentificare',
      register: 'Înregistrare',
      email: 'Email',
      password: 'Parolă',
      forgotPassword: 'Ai uitat parola?',
      noAccount: 'Nu ai cont?',
      hasAccount: 'Ai deja cont?',
      loginButton: 'Autentifică-te',
      registerButton: 'Înregistrează-te',
      loggingIn: 'Se autentifică...',
      registering: 'Se înregistrează...',
    },
    admin: {
      dashboard: 'Tablou de Bord',
      products: 'Galerie',
      messages: 'Mesaje',
      settings: 'Setări',
      addProduct: 'Adaugă Imagine',
      editProduct: 'Editează Imagine',
      deleteProduct: 'Șterge Imagine',
      save: 'Salvează',
      cancel: 'Anulează',
      delete: 'Șterge',
      confirm: 'Confirmă',
    },
    common: {
      loading: 'Se încarcă...',
      save: 'Salvează',
      cancel: 'Anulează',
      delete: 'Șterge',
      edit: 'Editează',
      close: 'Închide',
      back: 'Înapoi',
      next: 'Următorul',
      previous: 'Anterior',
      search: 'Caută',
      filter: 'Filtrează',
      sort: 'Sortează',
      viewMore: 'Vezi mai mult',
      viewLess: 'Vezi mai puțin',
    },
    stats: {
      products: 'Produse premium',
      experience: 'Ani de experiență',
      clients: 'Clienți mulțumiți',
    },
    footer: {
      about: 'Despre Noi',
      aboutText: 'RIGHT MOB este destinația ta principală pentru mobilier de lux și stil de viață premium.',
      quickLinks: 'Link-uri Rapide',
      followUs: 'Urmărește-ne',
      rights: 'Toate drepturile rezervate.',
    },
  },
  en: {
    nav: {
      home: 'Home',
      products: 'Gallery',
      about: 'About',
      contact: 'Contact',
      favorites: 'Favorites',
      tryRoom: 'Try in My Room',
      admin: 'Admin',
      logout: 'Logout',
    },
    hero: {
      title: 'RightMob',
      subtitle: 'Transform your space with luxury furniture crafted for unmatched comfort and style',
      cta: 'Explore collection',
      stats: {
        happyClients: 'Happy clients',
        products: 'Premium products',
        experience: 'Years experience',
      },
    },
    tryRoom: {
      title: 'Try furniture in your room',
      subtitle: 'See how our furniture looks in your own space before you buy',
      cta: 'Try now',
      previewBadge: 'Live',
      previewTitle: 'Live preview',
      previewSubtitle: 'Place furniture in seconds',
      previewAlt: 'Live furniture preview',
    },
    videoSection: {
      badge: 'Discover our story',
      title: 'Excellence in\nevery detail',
      description: 'Every piece of RightMob furniture is the result of a deep passion for design, premium materials, and impeccable attention to detail. From concept to completion, we create spaces that inspire.',
      cta: 'Request a consultation',
      stat1Label: 'Projects completed',
      stat2Label: 'Client satisfaction',
    },
    currency: {
      changeLabel: 'Change price currency',
    },
    collections: {
      title: 'Our collections',
      subtitle: 'Quality furniture for home and office',
      viewAll: 'View gallery',
      viewDetails: 'View details',
      itemsLabel: 'products',
      cards: {
        living: {
          title: 'Living Room',
          description: 'Comfort and elegance for your relaxation space',
        },
        bedroom: {
          title: 'Bedroom',
          description: 'A calm, stylish retreat for perfect rest',
        },
        kitchen: {
          title: 'Kitchen',
          description: 'Functional design for the heart of your home',
        },
      },
    },
    whyUs: {
      badge: 'Why RIGHT MOB?',
      title: 'Excellence in every aspect',
      subtitle: 'Well-made furniture, delivery and installation included.',
      quality: {
        title: 'Premium quality',
        description: 'Good materials, careful execution.',
      },
      warranty: {
        title: '10-year warranty',
        description: 'We offer a 10-year warranty on our products.',
      },
      delivery: {
        title: 'Free delivery',
        description: 'Free delivery for orders over 5000 RON.',
      },
      design: {
        title: 'Unique design',
        description: 'Custom pieces made to your project.',
      },
      stats: {
        satisfaction: 'Customer satisfaction',
        delivery: 'Fast delivery',
        experience: 'Years experience',
        rating: 'Average rating',
      },
    },
    testimonials: {
      title: 'What our clients say',
      subtitle: 'Client feedback on working with us.',
      empty: 'No reviews yet.',
    },
    products: {
      title: 'Our products',
      all: 'All',
      search: 'Search products...',
      noResults: "We couldn't find any products matching your criteria",
      tryAgain: 'Try adjusting your filters or search for something else',
      addToFavorites: 'Add to favorites',
      removeFromFavorites: 'Remove from favorites',
      productsCount: 'products',
      filters: {
        title: 'Filters',
        reset: 'Reset',
        categories: 'Categories',
        priceRange: 'Price range',
        min: 'Min',
        max: 'Max',
        quick: 'Quick filters',
        newest: 'New products',
        bestseller: 'Bestseller',
      },
      sort: {
        recommended: 'Recommended',
        newest: 'Newest',
        priceAsc: 'Price: Low to High',
        priceDesc: 'Price: High to Low',
        rating: 'Rating',
        name: 'Name A-Z',
      },
      view: {
        grid: 'Grid view',
        list: 'List view',
      },
      empty: {
        title: 'No products found',
        subtitle: 'Try adjusting filters to see more results',
        reset: 'Reset filters',
      },
      badges: {
        new: 'New',
        bestseller: 'Bestseller',
      },
      reviews: 'reviews',
      categories: {
        all: 'All',
        living: 'Living Room',
        bedroom: 'Bedroom',
        dining: 'Kitchen',
        office: 'Office',
        hall: 'Hallway',
        bathroom: 'Bathroom',
        kids: 'Kids Room',
        garden: 'Garden',
      },
    },
    productDetail: {
      loading: 'Loading...',
      notFoundTitle: 'Product not found',
      backToProducts: 'Back to products',
      newBadge: 'New',
      zoomHint: 'Click to zoom',
      bestseller: 'Bestseller',
      inStock: 'In stock',
      outOfStock: 'Out of stock',
      saveLabel: 'You save',
      colorAvailable: 'Available color',
      colorsAvailable: 'Available colors',
      soldOut: 'Sold out',
      deliveryTitle: 'Free Delivery',
      deliverySubtitle: 'In 2-3 business days',
      warrantyTitle: '10-Year Warranty',
      warrantySubtitle: 'Quality products',
      featuresTitle: 'Features',
      materialsTitle: 'Materials',
      dimensionsTitle: 'Dimensions',
      widthLabel: 'Width',
      heightLabel: 'Height',
      depthLabel: 'Depth',
      relatedTitle: 'Related Products',
      reviewsTitle: 'Reviews',
      noReviews: 'No reviews displayed.',
      ratingLabel: 'Rating',
      reviewTitleLabel: 'Review title',
      reviewTitlePlaceholder: 'Short summary (optional)',
      addComment: 'Add a review',
      reviewDetailsHint: 'Briefly describe your experience, product quality, and delivery.',
      authorPlaceholder: 'Your name (optional)',
      iAmOwner: 'I am the owner of this product',
      submitReview: 'Submit',
      reviewSent: 'Thank you! Your review has been added.',
    },
    favorites: {
      title: 'Your Favorite Products',
      empty: "You don't have any favorite products yet",
      emptyDesc: 'Start exploring our collection and add your favorite items',
      browse: 'Browse Products',
      view: 'View',
      remove: 'Remove from favorites',
      backToProducts: 'Back to products',
    },
    gallery: {
      title: 'Furniture',
      fromOurGallery: 'From our gallery',
      sortBy: 'Sort',
      sortNewest: 'Newest',
      sortNameAsc: 'Name A → Z',
      sortNameDesc: 'Name Z → A',
      sortCategory: 'Category',
      all: 'All',
      product: 'item',
      products: 'items',
      inCategory: 'in',
      noProducts: 'No items here',
      noProductsHint: 'Add items from the admin panel.',
      noProductsInCategory: 'No items in category "{category}".',
      showAllCategories: 'Show all categories',
      viewDetails: 'View details',
      backToGallery: 'Back to gallery',
      details: 'Details',
      aboutProject: 'About project',
      loading: 'Loading...',
      notFound: 'Item not found',
      notFoundHint: 'It may have been removed or the link is incorrect.',
      noDescription: 'No description',
      images: 'images',
      moreImages: 'images',
      reviewsTitle: 'Reviews',
      noReviews: 'No reviews displayed.',
      categories: { living: 'Living room', dormitor: 'Bedroom', bucatarie: 'Kitchen', birou: 'Office', office: 'Office', hol: 'Hall', baie: 'Bathroom', copii: "Children's room", gradina: 'Garden' },
      detailLabels: {
        'Tip': 'Type',
        'Descriere': 'Description',
        'Țara de origine': 'Country of origin',
        'Producător': 'Manufacturer',
        'Formă bucătărie': 'Kitchen shape',
        'Material fațadă': 'Facade material',
        'Material carcasă': 'Carcass material',
        'Culoare': 'Color',
        'Sistem deschidere': 'Opening system',
        'Tip sertare': 'Drawer type',
        'Balamale': 'Hinges',
        'Cornisă': 'Cornice',
        'Mânere': 'Handles',
        'Blat': 'Countertop',
        'Glisiere': 'Slides',
        'Termen de fabricare': 'Manufacturing term',
        'Proiect': 'Project',
        'Materiale fațadă': 'Facade materials',
        'Tip sertare / glisiere': 'Drawer / slide type',
        'Produs': 'Product',
        'Dimensiuni': 'Dimensions',
        'Material': 'Material',
      },
    },
    contact: {
      title: 'Contact Us',
      subtitle: 'Have questions? We would love to hear from you',
      formTitle: 'Send us a message',
      formSubtitle: 'Fill out the form and we will contact you quickly',
      name: 'Full name',
      email: 'Email',
      phone: 'Phone',
      optional: 'optional',
      message: 'Your message',
      messagePlaceholder: 'Tell us what type of furniture you are looking for, for what space and what style you prefer...',
      send: 'Send message',
      sending: 'Sending...',
      success: 'Message sent successfully!',
      error: 'An error occurred. Please try again.',
      privacy: 'By submitting the form you agree to the processing of data in accordance with the privacy policy.',
      badge: 'We are here for you',
      followUs: 'Follow Us',
      socialSubtitle: 'Stay updated with our products and offers',
      placeholders: {
        name: 'John Doe',
        email: 'john@email.com',
        phone: '+373 69 123 456',
      },
      showroom: {
        title: 'Office',
        line1: '123 Stefan cel Mare Street',
        line2: 'Chisinau, Moldova',
        hours: 'Mon – Sat: 10:00 – 20:00',
      },
      openInMaps: 'Open in Google Maps',
      phoneHours: 'Mon – Fri: 09:00 – 18:00',
      emailHours: 'We reply within 24h',
      info: {
        email: 'Email',
        phone: 'Phone',
        address: 'Address',
      },
    },
    about: {
      title: 'About RIGHT MOB',
      badge: 'Our story',
      subtitle: 'With over 15 years of experience, we bring elegance, quality and authentic design to our customers\' homes.',
      storyTitle: 'Passion for beautiful',
      storyText1: 'It all started from the desire to transform living spaces into places full of personality and comfort. We collaborate with trusted designers and manufacturers to bring premium, well-thought-out and durable furniture.',
      storyText2: 'We offer not only pieces of furniture, but complete solutions for living room, bedroom, kitchen and office - from selection to delivery and installation.',
      stats: {
        experience: 'Years experience',
        clients: 'Happy clients',
        delivered: 'Pieces delivered',
      },
      valuesTitle: 'Our values',
      values: {
        quality: { title: 'Premium quality', desc: 'High production standards and selected materials' },
        passion: { title: 'Passion', desc: 'Dedication for every project and client' },
        innovation: { title: 'Innovation', desc: 'Contemporary and functional design' },
      },
      deliveryTitle: 'Delivery & installation',
      deliverySteps: {
        step1: { title: 'Order confirmed', desc: 'Confirmation within maximum 2 hours' },
        step2: { title: 'Preparation & verification', desc: 'Products verified and carefully packaged' },
        step3: { title: 'Free delivery', desc: 'Transport in 2-3 working days' },
        step4: { title: 'Professional installation', desc: 'Our team installs at your location' },
      },
      schedule: 'Installation schedule:',
      scheduleTime: 'Monday – Friday, 09:00 – 17:00. Flexible scheduling.',
      ctaText: 'Want to discuss your project?',
      ctaButton: 'Contact us',
      whoWeAre: 'Who are we?',
      customFurnitureTitle: 'Custom furniture, designed for you',
      whoWeAreP1: 'We are a company specialized in custom furniture production, dedicated to creating personalized solutions that combine functionality, aesthetics and durability. We work directly with each client to transform ideas, sketches or space requirements into furniture pieces made exactly to dimensions, style and budget.',
      whoWeAreP2: 'We make furniture for homes, commercial spaces and special projects, covering the entire process: consultancy, design, material selection, production and installation. Each project is executed with attention to detail, using quality materials and modern technologies, to ensure durability over time and an impeccable finish.',
      whoWeAreP3: 'We believe that furniture should not only be beautiful, but also adapted to the real way of use. That is why each project is thought practically, optimized for the available space and made to offer comfort, efficiency and identity to every interior.',
      missionLabel: 'Our mission',
      missionQuote: 'Our mission is to offer clients correct, well-executed and durable solutions, building relationships based on trust, transparency and professionalism.',
      whyChooseUs: 'Why choose us?',
      whyChooseUsTitle: 'Complete process, from idea to installation',
      whyChooseUsP1: 'We cover the entire process: from consultancy and design to production and installation. Each project is thought practically and optimized for your space, with quality materials and impeccable finish.',
      whyChooseUsP2: 'We build long-term relationships based on trust, transparency and professionalism.',
    },
    tryRoomPage: {
      title: 'Try in My Room',
      back: 'Back',
      chooseMode: 'Choose capture mode',
      useCamera: 'Use Camera',
      uploadImage: 'Upload Image',
      loadingCamera: 'Loading camera...',
      uploadAnImage: 'Upload an image',
      redo: 'Redo',
      delete: 'Delete',
      export: 'Export',
      preparingImage: 'Preparing image...',
      upload: 'Upload',
      takePhoto: 'Take photo',
      switch: 'Switch',
      chooseProduct: 'Choose a product',
      dragUp: '👆 Drag up',
      searchPlaceholder: 'Search products...',
      allCategories: 'All',
      outOfStock: 'Out of stock',
      noProducts: 'No products found',
      helpLabel: 'Help',
      helpTitle: 'How to use',
      helpStep1Title: 'Take a photo',
      helpStep1Desc: 'Use camera or upload an image of your room',
      helpStep2Title: 'Add furniture',
      helpStep2Desc: 'Select products from the drawer below',
      helpStep3Title: 'Arrange',
      helpStep3DescDesktop: 'Desktop:',
      helpStep3DescDesktopDetails: 'Click & drag, Mouse wheel = zoom, Shift + wheel = rotate',
      helpStep3DescMobile: 'Mobile:',
      helpStep3DescMobileDetails: '1 finger = move, 2 fingers = zoom & rotate',
      helpStep4Title: 'Export',
      helpStep4Desc: 'Download the final image with the Export button',
      colorSelectorTitle: 'Choose color',
      colorSelectorSubtitle: 'Select the desired color for this product',
    },
    auth: {
      login: 'Login',
      register: 'Register',
      email: 'Email',
      password: 'Password',
      forgotPassword: 'Forgot password?',
      noAccount: "Don't have an account?",
      hasAccount: 'Already have an account?',
      loginButton: 'Log In',
      registerButton: 'Register',
      loggingIn: 'Logging in...',
      registering: 'Registering...',
    },
    admin: {
      dashboard: 'Dashboard',
      products: 'Products',
      messages: 'Messages',
      settings: 'Settings',
      addProduct: 'Add Product',
      editProduct: 'Edit Product',
      deleteProduct: 'Delete Product',
      save: 'Save',
      cancel: 'Cancel',
      delete: 'Delete',
      confirm: 'Confirm',
    },
    common: {
      loading: 'Loading...',
      save: 'Save',
      cancel: 'Cancel',
      delete: 'Delete',
      edit: 'Edit',
      close: 'Close',
      back: 'Back',
      next: 'Next',
      previous: 'Previous',
      search: 'Search',
      filter: 'Filter',
      sort: 'Sort',
      viewMore: 'View More',
      viewLess: 'View Less',
    },
    stats: {
      products: 'Premium products',
      experience: 'Years of experience',
      clients: 'Happy clients',
    },
    footer: {
      about: 'About Us',
      aboutText: 'RIGHT MOB is your premier destination for luxury furniture and premium lifestyle.',
      quickLinks: 'Quick Links',
      followUs: 'Follow Us',
      rights: 'All rights reserved.',
    },
  },
  ru: {
    nav: {
      home: 'Главная',
      products: 'Галерея',
      about: 'О нас',
      contact: 'Контакты',
      favorites: 'Избранное',
      tryRoom: 'Примерить в комнате',
      admin: 'Админ',
      logout: 'Выход',
    },
    hero: {
      title: 'RightMob',
      subtitle: 'Преобразите ваше пространство роскошной мебелью, созданной для непревзойденного комфорта и стиля',
      cta: 'Изучить коллекцию',
      stats: {
        happyClients: 'Довольных клиентов',
        products: 'Премиум товаров',
        experience: 'Лет опыта',
      },
    },
    tryRoom: {
      title: 'Примерьте мебель в комнате',
      subtitle: 'Посмотрите, как наша мебель будет выглядеть в вашем пространстве перед покупкой',
      cta: 'Попробовать сейчас',
      previewBadge: 'Live',
      previewTitle: 'Предпросмотр вживую',
      previewSubtitle: 'Разместите мебель за несколько секунд',
      previewAlt: 'Предпросмотр мебели в комнате',
    },
    videoSection: {
      badge: 'Откройте нашу историю',
      title: 'Совершенство в\nкаждой детали',
      description: 'Каждый предмет мебели RightMob — это результат глубокой страсти к дизайну, премиальным материалам и безупречному вниманию к деталям. От идеи до воплощения мы создаём пространства, которые вдохновляют.',
      cta: 'Запросить консультацию',
      stat1Label: 'Проектов реализовано',
      stat2Label: 'Удовлетворённость клиентов',
    },
    currency: {
      changeLabel: 'Изменить валюту цены',
    },
    collections: {
      title: 'Наши коллекции',
      subtitle: 'Качественная мебель для дома и офиса',
      viewAll: 'Смотреть галерею',
      viewDetails: 'Подробнее',
      itemsLabel: 'товаров',
      cards: {
        living: {
          title: 'Гостиная',
          description: 'Комфорт и элегантность для зоны отдыха',
        },
        bedroom: {
          title: 'Спальня',
          description: 'Спокойствие и стиль для идеального сна',
        },
        kitchen: {
          title: 'Кухня',
          description: 'Функциональный дизайн для сердца дома',
        },
      },
    },
    whyUs: {
      badge: 'Почему RIGHT MOB?',
      title: 'Совершенство в каждом аспекте',
      subtitle: 'Качественная мебель, доставка и монтаж.',
      quality: {
        title: 'Премиум качество',
        description: 'Хорошие материалы, аккуратная работа.',
      },
      warranty: {
        title: 'Гарантия 10 лет',
        description: 'Предлагаем гарантию 10 лет на продукцию.',
      },
      delivery: {
        title: 'Бесплатная доставка',
        description: 'Доставка бесплатно при заказе от 5000 RON.',
      },
      design: {
        title: 'Уникальный дизайн',
        description: 'Изделия на заказ по вашему проекту.',
      },
      stats: {
        satisfaction: 'Удовлетворенность клиентов',
        delivery: 'Быстрая доставка',
        experience: 'Лет опыта',
        rating: 'Средний рейтинг',
      },
    },
    testimonials: {
      title: 'Что говорят наши клиенты',
      subtitle: 'Отзывы клиентов о работе с нами.',
      empty: 'Пока нет отзывов.',
    },
    products: {
      title: 'Наши товары',
      all: 'Все',
      search: 'Поиск товаров...',
      noResults: 'Мы не смогли найти товары, соответствующие вашим критериям',
      tryAgain: 'Попробуйте изменить фильтры или найти что-то другое',
      addToFavorites: 'Добавить в избранное',
      removeFromFavorites: 'Убрать из избранного',
      productsCount: 'товаров',
      filters: {
        title: 'Фильтры',
        reset: 'Сбросить',
        categories: 'Категории',
        priceRange: 'Диапазон цены',
        min: 'Мин',
        max: 'Макс',
        quick: 'Быстрые фильтры',
        newest: 'Новые товары',
        bestseller: 'Бестселлер',
      },
      sort: {
        recommended: 'Рекомендуемые',
        newest: 'Самые новые',
        priceAsc: 'Цена по возрастанию',
        priceDesc: 'Цена по убыванию',
        rating: 'Рейтинг',
        name: 'Имя A-Z',
      },
      view: {
        grid: 'Сетка',
        list: 'Список',
      },
      empty: {
        title: 'Товары не найдены',
        subtitle: 'Попробуйте изменить фильтры, чтобы увидеть больше результатов',
        reset: 'Сбросить фильтры',
      },
      badges: {
        new: 'Новинка',
        bestseller: 'Бестселлер',
      },
      reviews: 'отзывов',
      categories: {
        all: 'Все',
        living: 'Гостиная',
        bedroom: 'Спальня',
        dining: 'Кухня',
        office: 'Офис',
        hall: 'Прихожая',
        bathroom: 'Ванная',
        kids: 'Детская',
        garden: 'Сад',
      },
    },
    productDetail: {
      loading: 'Загрузка...',
      notFoundTitle: 'Товар не найден',
      backToProducts: 'Назад к товарам',
      newBadge: 'Новинка',
      zoomHint: 'Нажмите для увеличения',
      bestseller: 'Бестселлер',
      inStock: 'В наличии',
      outOfStock: 'Нет в наличии',
      saveLabel: 'Вы экономите',
      colorAvailable: 'Доступный цвет',
      colorsAvailable: 'Доступные цвета',
      soldOut: 'Распродано',
      deliveryTitle: 'Бесплатная доставка',
      deliverySubtitle: 'За 2-3 рабочих дня',
      warrantyTitle: 'Гарантия 10 лет',
      warrantySubtitle: 'Качественные товары',
      featuresTitle: 'Характеристики',
      materialsTitle: 'Материалы',
      dimensionsTitle: 'Размеры',
      widthLabel: 'Ширина',
      heightLabel: 'Высота',
      depthLabel: 'Глубина',
      relatedTitle: 'Похожие товары',
      reviewsTitle: 'Отзывы',
      noReviews: 'Нет отзывов для отображения.',
      ratingLabel: 'Оценка',
      reviewTitleLabel: 'Заголовок отзыва',
      reviewTitlePlaceholder: 'Краткий итог (необязательно)',
      addComment: 'Добавить отзыв',
      reviewDetailsHint: 'Кратко опишите впечатление, качество и доставку.',
      authorPlaceholder: 'Ваше имя (необязательно)',
      iAmOwner: 'Я владелец этого товара',
      submitReview: 'Отправить',
      reviewSent: 'Спасибо! Ваш отзыв добавлен.',
    },
    favorites: {
      title: 'Ваши избранные товары',
      empty: 'У вас пока нет избранных товаров',
      emptyDesc: 'Начните изучать нашу коллекцию и добавьте ваши любимые товары',
      browse: 'Просмотреть товары',
      view: 'Смотреть',
      remove: 'Убрать из избранного',
      backToProducts: 'Назад к товарам',
    },
    gallery: {
      title: 'Мебель',
      fromOurGallery: 'Из нашей галереи',
      sortBy: 'Сортировка',
      sortNewest: 'Сначала новые',
      sortNameAsc: 'Имя А → Я',
      sortNameDesc: 'Имя Я → А',
      sortCategory: 'Категория',
      all: 'Все',
      product: 'товар',
      products: 'товаров',
      inCategory: 'в',
      noProducts: 'Здесь нет товаров',
      noProductsHint: 'Добавьте товары в панели администратора.',
      noProductsInCategory: 'Нет товаров в категории «{category}».',
      showAllCategories: 'Показать все категории',
      viewDetails: 'Подробнее',
      backToGallery: 'Назад в галерею',
      details: 'Детали',
      aboutProject: 'О проекте',
      loading: 'Загрузка...',
      notFound: 'Товар не найден',
      notFoundHint: 'Возможно, он был удалён или ссылка неверна.',
      noDescription: 'Без описания',
      images: 'фото',
      moreImages: 'фото',
      reviewsTitle: 'Отзывы',
      noReviews: 'Нет отзывов для отображения.',
      categories: { living: 'Гостиная', dormitor: 'Спальня', bucatarie: 'Кухня', birou: 'Офис', office: 'Офис', hol: 'Прихожая', baie: 'Ванная', copii: 'Детская', gradina: 'Сад' },
      detailLabels: {
        'Tip': 'Тип',
        'Descriere': 'Описание',
        'Țara de origine': 'Страна происхождения',
        'Producător': 'Производитель',
        'Formă bucătărie': 'Форма кухни',
        'Material fațadă': 'Материал фасада',
        'Material carcasă': 'Материал корпуса',
        'Culoare': 'Цвет',
        'Sistem deschidere': 'Система открывания',
        'Tip sertare': 'Тип ящиков',
        'Balamale': 'Петли',
        'Cornisă': 'Карниз',
        'Mânere': 'Ручки',
        'Blat': 'Столешница',
        'Glisiere': 'Направляющие',
        'Termen de fabricare': 'Срок изготовления',
        'Proiect': 'Проект',
        'Materiale fațadă': 'Материалы фасада',
        'Tip sertare / glisiere': 'Тип ящиков / направляющих',
        'Produs': 'Продукт',
        'Dimensiuni': 'Размеры',
        'Material': 'Материал',
      },
    },
    contact: {
      title: 'Свяжитесь с нами',
      subtitle: 'Есть вопросы? Мы будем рады услышать вас',
      formTitle: 'Отправьте нам сообщение',
      formSubtitle: 'Заполните форму, и мы свяжемся с вами быстро',
      name: 'Полное имя',
      email: 'Email',
      phone: 'Телефон',
      optional: 'необязательно',
      message: 'Ваше сообщение',
      messagePlaceholder: 'Расскажите нам, какой тип мебели вы ищете, для какого помещения и какой стиль предпочитаете...',
      send: 'Отправить сообщение',
      sending: 'Отправка...',
      success: 'Сообщение успешно отправлено!',
      error: 'Произошла ошибка. Пожалуйста, попробуйте снова.',
      privacy: 'Отправляя форму, вы соглашаетесь на обработку данных в соответствии с политикой конфиденциальности.',
      badge: 'Мы здесь для вас',
      followUs: 'Следите за нами',
      socialSubtitle: 'Будьте в курсе наших товаров и предложений',
      placeholders: {
        name: 'Ион Попеску',
        email: 'ion@email.com',
        phone: '+373 69 123 456',
      },
      showroom: {
        title: 'Офис',
        line1: 'ул. Штефан чел Маре, 123',
        line2: 'Кишинев, Молдова',
        hours: 'Пн – Сб: 10:00 – 20:00',
      },
      openInMaps: 'Открыть в Google Картах',
      phoneHours: 'Пн – Пт: 09:00 – 18:00',
      emailHours: 'Отвечаем в течение 24 часов',
      info: {
        email: 'Email',
        phone: 'Телефон',
        address: 'Адрес',
      },
    },
    about: {
      title: 'О бренде RIGHT MOB',
      badge: 'Наш подход',
      subtitle: 'Мы создаем мебель для живых интерьеров, где важны комфорт, эстетика и практичность в каждом дне.',
      storyTitle: 'Как мы работаем',
      storyText1: 'Мы отбираем надежных производителей и материалы, чтобы каждая вещь служила долго и выглядела безупречно.',
      storyText2: 'Помогаем выбрать подходящие решения для дома и офиса — от подбора до доставки и установки.',
      stats: {
        experience: 'Лет опыта',
        clients: 'Довольных клиентов',
        delivered: 'Доставленных изделий',
      },
      valuesTitle: 'Наши ценности',
      values: {
        quality: { title: 'Премиум качество', desc: 'Высокие стандарты производства и отобранные материалы' },
        passion: { title: 'Страсть', desc: 'Преданность каждому проекту и клиенту' },
        innovation: { title: 'Инновации', desc: 'Современный и функциональный дизайн' },
      },
      deliveryTitle: 'Доставка и установка',
      deliverySteps: {
        step1: { title: 'Заказ подтвержден', desc: 'Подтверждение в течение 2 часов' },
        step2: { title: 'Подготовка и проверка', desc: 'Товары проверены и тщательно упакованы' },
        step3: { title: 'Бесплатная доставка', desc: 'Транспортировка за 2-3 рабочих дня' },
        step4: { title: 'Профессиональная установка', desc: 'Наша команда установит на вашем месте' },
      },
      schedule: 'График установки:',
      scheduleTime: 'Понедельник – Пятница, 09:00 – 17:00. Гибкий график.',
      ctaText: 'Хотите обсудить свой проект?',
      ctaButton: 'Свяжитесь с нами',
      whoWeAre: 'Кто мы?',
      customFurnitureTitle: 'Мебель на заказ, созданная для вас',
      whoWeAreP1: 'Мы компания, специализирующаяся на производстве мебели на заказ, создающая индивидуальные решения, сочетающие функциональность, эстетику и долговечность. Мы работаем напрямую с каждым клиентом, чтобы превратить идеи, эскизы или потребности в пространстве в мебельные изделия, изготовленные точно по размерам, стилю и бюджету.',
      whoWeAreP2: 'Мы изготавливаем мебель для жилых помещений, коммерческих пространств и специальных проектов, охватывая весь процесс: консультация, проектирование, выбор материалов, производство и монтаж. Каждый проект выполняется с вниманием к деталям, с использованием качественных материалов и современных технологий для обеспечения долговечности и безупречной отделки.',
      whoWeAreP3: 'Мы считаем, что мебель должна быть не только красивой, но и адаптированной к реальному способу использования. Поэтому каждый проект продумывается практично, оптимизируется для доступного пространства и создается так, чтобы обеспечить комфорт, эффективность и индивидуальность каждому интерьеру.',
      missionLabel: 'Наша миссия',
      missionQuote: 'Наша миссия — предлагать клиентам правильные, качественно выполненные и долговечные решения, строя отношения на основе доверия, прозрачности и профессионализма.',
      whyChooseUs: 'Почему выбрать нас?',
      whyChooseUsTitle: 'Полный процесс: от идеи до монтажа',
      whyChooseUsP1: 'Мы охватываем весь процесс: от консультации и проектирования до производства и монтажа. Каждый проект продуман практично и оптимизирован для вашего пространства, с качественными материалами и безупречной отделкой.',
      whyChooseUsP2: 'Мы строим долгосрочные отношения на основе доверия, прозрачности и профессионализма.',
    },
    tryRoomPage: {
      title: 'Try in My Room',
      back: 'Назад',
      chooseMode: 'Выберите режим захвата',
      useCamera: 'Использовать камеру',
      uploadImage: 'Загрузить изображение',
      loadingCamera: 'Загрузка камеры...',
      uploadAnImage: 'Загрузить изображение',
      redo: 'Переделать',
      delete: 'Удалить',
      export: 'Экспорт',
      preparingImage: 'Подготовка изображения...',
      upload: 'Загрузить',
      takePhoto: 'Сделать фото',
      switch: 'Переключить',
      chooseProduct: 'Выберите товар',
      dragUp: '👆 Потяните вверх',
      searchPlaceholder: 'Поиск товаров...',
      allCategories: 'Все',
      outOfStock: 'Нет в наличии',
      noProducts: 'Товары не найдены',
      helpLabel: 'Помощь',
      helpTitle: 'Как использовать',
      helpStep1Title: 'Сделайте фото',
      helpStep1Desc: 'Используйте камеру или загрузите изображение вашей комнаты',
      helpStep2Title: 'Добавьте мебель',
      helpStep2Desc: 'Выберите товары из списка ниже',
      helpStep3Title: 'Расположите',
      helpStep3DescDesktop: 'Компьютер:',
      helpStep3DescDesktopDetails: 'Нажмите и перетащите, Колесико мыши = масштаб, Shift + колесико = поворот',
      helpStep3DescMobile: 'Мобильный:',
      helpStep3DescMobileDetails: '1 палец = перемещение, 2 пальца = масштаб & поворот',
      helpStep4Title: 'Экспорт',
      helpStep4Desc: 'Загрузите финальное изображение кнопкой Экспорт',
      colorSelectorTitle: 'Выберите цвет',
      colorSelectorSubtitle: 'Выберите желаемый цвет для этого товара',
    },
    auth: {
      login: 'Вход',
      register: 'Регистрация',
      email: 'Email',
      password: 'Пароль',
      forgotPassword: 'Забыли пароль?',
      noAccount: 'Нет аккаунта?',
      hasAccount: 'Уже есть аккаунт?',
      loginButton: 'Войти',
      registerButton: 'Зарегистрироваться',
      loggingIn: 'Вход...',
      registering: 'Регистрация...',
    },
    admin: {
      dashboard: 'Панель управления',
      products: 'Товары',
      messages: 'Сообщения',
      settings: 'Настройки',
      addProduct: 'Добавить товар',
      editProduct: 'Редактировать товар',
      deleteProduct: 'Удалить товар',
      save: 'Сохранить',
      cancel: 'Отменить',
      delete: 'Удалить',
      confirm: 'Подтвердить',
    },
    common: {
      loading: 'Загрузка...',
      save: 'Сохранить',
      cancel: 'Отменить',
      delete: 'Удалить',
      edit: 'Редактировать',
      close: 'Закрыть',
      back: 'Назад',
      next: 'Далее',
      previous: 'Предыдущий',
      search: 'Поиск',
      filter: 'Фильтр',
      sort: 'Сортировка',
      viewMore: 'Показать больше',
      viewLess: 'Показать меньше',
    },
    stats: {
      products: 'Премиум продукты',
      experience: 'Лет опыта',
      clients: 'Довольных клиентов',
    },
    footer: {
      about: 'О нас',
      aboutText: 'RIGHT MOB - ваше главное направление для роскошной мебели и премиум стиля жизни.',
      quickLinks: 'Быстрые ссылки',
      followUs: 'Следите за нами',
      rights: 'Все права защищены.',
    },
  },
};

  export const getStaticTranslation = (lang: 'ro' | 'en' | 'ru', key: string): string => {
    const keys = key.split('.');
    let value: any = (translations as any)[lang];
    for (const k of keys) {
      if (value && typeof value === 'object' && k in value) {
        value = value[k];
      } else {
        let fallback: any = (translations as any)['ro'];
        for (const fk of keys) {
          if (fallback && typeof fallback === 'object' && fk in fallback) fallback = fallback[fk];
          else return '';
        }
        return typeof fallback === 'string' ? fallback : '';
      }
    }
    return typeof value === 'string' ? value : '';
  };
